# BlockPhysics

Fire:
  NoFireSpread: ON
  LogToConsole: ON
  ShowWarnings: ON

Explosions:
  CancelAllTNT: ON
  CancelCreepa: ON
  CancelWither: ON
  CancelGhasts: ON

Lava:
  NoGlobalFlow: ON
  NoBucketFlow: ON
  InfinitePool: ON
  ObsidianFlow: ON
	
Water:
  NoGlobalFlow: ON
  NoBucketFlow: ON
  InfinitePool: ON
  ObsidianFlow: ON

Vines:
  NoVinesInAir: ON
  SheersAssist: ON