# BlockPhysics

Fire:
  NoFireSpread: ON
  ShowWarnings: ON
Lava:
  NoGlobalFlow: ON
  InfiniteFlow: ON
  ObsidianFlow: ON
Water:
  NoGlobalFlow: ON
  InfiniteFlow: ON
  ObsidianFlow: ON
Vines:
  VinesOnBlock: ON
  NoVinesInAir: ON
Version:
  ConfigYMLVer: 5