name: BlockPhysics
main: com.accmss.blockphysics.BlockPhysics
version: 1.5.5
description: BlockPhysics permissions.

commands:
   flowon:
      description: Enables liquid flow
      usage: /flowon
      permission: blockphysics.admin
      permisison-message: You don't have permissions
   flowoff:
      description: Disables liquid flow
      usage: /flowoff
      permission: blockphysics.admin
      permisison-message: You don't have permissions